permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 琼小资
  email: vocient@gmail.com
  link: http://vicent900527.github.io/
  #weibo: http://weibo.com/yansu0711
  github: http://github.com/vicent900528

# 站点信息
title: 琼小资的博客 
description: 琼小资的博客
url: http://vicent900527.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /images/my_favicon.jpg
favicon: /images/bitbug_favicon.ico

# google analytics 设置
ga:
  id: UA-58303639-2
  url: vicent900527.github.io

# disqus 设置
disqus:
  shortname: xluo